M48
; DRILL file {KiCad 9.0.1} date 2025-04-08T15:50:02+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-08T15:50:02+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X124.385Y-134.27
X130.165Y-134.27
T2
X95.185Y-139.2
X98.185Y-139.2
M30
